---
- name: Check Disk Utilization
  hosts: localhost
  tasks:
    - name: Gather && File System Usage for testing..
      ansible.builtin.command: echo "this is the test"
      when: awx_webhook_payload.ref == "refs/heads/main"
      

