---
- name: Check Disk Utilization
  hosts: localhost
  tasks:
    - name: Gather && File System Usage for testing..
      ansible.builtin.command: "free -h" 
      when: "'{{ awx_webhook_payload.ref }}' == 'refs/heads/test-awx'"

