---
- name: Check Disk Utilization and Store in File.
  hosts: localhost
  tasks:
    - name: Gather File System Information .
      ansible.builtin.command: "df -h" 
      when: awx_webhook_payload.ref == "refs/heads/main"

      
    # - name: print payload
    #   debug: 
    #     msg: "{{ awx_webhook_payload.ref }}"
