---
- name: Trigger on AWX Webhook Payload Action Completed
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Check AWX Webhook Payload Action
      command: echo "Hi"
      when: "'{{ awx_webhook_payload.ref }}' == 'refs/heads/main'"

    
      

