---
- name: Trigger on AWX Webhook Payload Action Completed
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Check AWX Webhook Payload Action
      assert:
        that:
          - "'{{ awx_webhook_payload.status }}' == 'completed'"
        fail_msg: "Webhook payload action is not completed."
      when: awx_webhook_payload is defined

