name: Github actions
on:
  push:
    branches: [ main ]
  workflow_run:
    types:
      - completed
jobs:
    build:
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/main'
        steps:
            -   name: trigger
                run: echo "Hii"
                if: ${{ success() }}
       
