name: trigger

# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: main
    branches: main
    types:
      - awx
      - completed
jobs:
  process_payload:
    runs-on: ubuntu-latest
  
    steps:
      - id: step1
        run: echo "::set-output name=firstword::hello"
      # if: awx_webhook_event_type == 'workflow_job' &&  awx_webhook_payload.action == 'completed'
      # run: |
      #   # Add your custom script or commands here to handle the completed action
      #   echo "AWX webhook action is completed, performing additional tasks..."
