name: trigger

# Only trigger, when the build workflow succeeded
on:
  webhook:
    types:
      - awx
      - completed
jobs:
  process_payload:
    runs-on: ubuntu-latest
  
    steps:
    - name: Check if AWX action is completed
      if: github.event_name == 'webhook' && github.event.payload.action == 'completed'
      run: |
        # Add your custom script or commands here to handle the completed action
        echo "AWX webhook action is completed, performing additional tasks..."
